# Approach from https://mtlynch.io/painless-web-app-testing/

version: '3.2'

services:
  cypress:
    build: ./
    environment:
      - CYPRESS_baseUrl=https://english-classroom-staging.herokuapp.com/